### ISSUE TITLE
temperature sensors not shown the environmental overview

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus-html5-app#357] opened 2024-02-14 16:01 UTC
Temperature only devices don't seem to be shown in the environmental overview.

Present on mqtt:
![image](https://github.com/victronenergy/venus-html5-app/assets/6614648/498b5b3a-a8d3-4c83-a557-d64f4d5c5681)

Also on gui-v1:
![image](https://github.com/victronenergy/venus-html5-app/assets/6614648/264548a4-2a72-4769-bff8-ffd4f3474617)

But not on the marine app...

However, Ruuvi tags are shown, but there are of the same service type as the temperature sensor, i.e. temperature.
![image](https://github.com/victronenergy/venus-html5-app/assets/6614648/7dd563f7-ff47-4072-9a8f-0515d9dfebad)
![image](https://github.com/victronenergy/venus-html5-app/assets/6614648/1bccd6e2-0036-4282-b907-66f67edf5540)

**Comment by mr-manuel** [comment] 2024-02-19 10:18
Hello, I have the same issue and found out, that the Environment tile is only shown if the pressure is not `null`. Any number is accepted, even negative ones. Since only the Ruuvi tags have a pressure and they are the most used sensors this was not very obvious to find.

I checked the documentation and the pressure value should not be needed: https://github.com/victronenergy/venus/wiki/dbus#temperatures

You can make a simple test and send the payload `{"value": null}` to `N/{VRMID}/temperature/28/Pressure` and the tile should disappear. I made only the reversed test, since my temperature sensors were not shown. I send the payload `{"value": 0}` and the tile instantly appeared.

**Comment by martinbosma** [comment] 2024-02-19 10:45
Hi @mr-manuel I can confirm the same with the `N/{VRMID}/temperature/*/Humidity` topic. We'll look into this.

**Comment by mr-manuel** [comment] 2024-02-19 10:51
I searched a bit and probably the issue is in this script: https://github.com/victronenergy/venus-html5-app/blob/master/src/app/Marine2/components/boxes/EnvironmentOverview/EnvironmentOverview.tsx

**Comment by fwaalkens** [comment] 2024-02-20 09:01
Resolved in: https://github.com/victronenergy/venus-html5-app/pull/360. @mr-manuel thanks for your research efforts, should be fixed now.

**Closed by fwaalkens** 2024-02-20 09:01 UTC

**Comment by mr-manuel** [comment] 2024-02-20 09:12
Thanks, Is there a way to download a alpha/beta version that is already compiled? Would be nice to have the possibility as for gui-v2. It can be automated with a GitHub action.

**Comment by martinbosma** [comment] 2024-02-20 10:46
I'm afraid we don't have it available for every change, only for a release. The best we can do, is to make this part of VenusOS v3.30~xx asap.

**Comment by mr-manuel** [comment] 2024-02-20 10:58
@mpvader would it be an idea to also add a GitHub workflow to this repo that builds a new version once a day, week or any other action? Maybe this is not wanted.
