### ISSUE TITLE
Strange jumping of battery widgets

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus-html5-app#401] opened 2024-08-28 14:51 UTC
See at 14s in below video.

https://github.com/user-attachments/assets/d6a93216-54eb-486f-b0bb-693bac3afb65

**Comment by mman** [comment] 2024-08-28 15:06
I think this one is caused by the fact that 24v Lynx Smart BMS goes from _Charging_ / 100% to _Idle_  / 100% and therefore changes position.

The algorithm to sort batteries currently works as follows:

1. active battery service goes first
2. _charging_ goes before _discharging_ and that goes before _idle_
3. if they have the same parameters (active/nonactive) (charing/discharging/idle) they are sorted by their id

So the question perhaps is that we need to revisit how to actually sort all the available battery services in the system so that it makes more sense and does not possibly jump because battery state changes ...

**Comment by mman** [comment] 2024-08-29 15:52
@mpvader Do you have an idea how you would like the sorting algorithm to work to prevent accidental jumping and still be useful? Perhaps just sorting batteries with `active_battery_service: true` first and everything alphabetically by name? or id? ignoring the `state` and `soc` which can change over time?

**Comment by mman** [comment] 2024-09-03 16:31
Addressed by https://github.com/victronenergy/venus-html5-app/commit/38883e1a04650d4e7ee9e80ac16115bfe13184d2

**Closed by mman** 2024-09-03 16:31 UTC
Labels: bug
