### ISSUE TITLE
connect to the MQTT broker through the nginx websocket

### ISSUE THREAD

**Issue by jhofstee** [victronenergy/venus-html5-app#384] opened 2024-06-14 09:27 UTC
In the near future (optional) encryption and authentication will be added for the LAN services, see https://github.com/victronenergy/venus/issues/1255. Both will be handled by the webserver (nginx). In order to make at least authentication work, the venus-html5-app should no longer connect directly to the MQTT websocket, but through the webserver instead. The url is http://[host]/websocket-mqtt or https://[host]/websocket-mqtt.

The current Venus releases already include mentioned path. Accessing the app over https:// will redirect to http:// at the moment.

**Comment by mman** [comment] 2024-07-22 14:00
Fixed via https://github.com/victronenergy/victron-mfd-modules/pull/4

**Closed by mman** 2024-07-22 14:00 UTC
Labels: enhancement

**Comment by mr-manuel** [comment] 2024-08-06 09:42
Does this also fix the connecting loop, when opening the MFD app via https?

![grafik](https://github.com/user-attachments/assets/d1c8b2ef-a3e9-4a63-8b8c-a6a5a3fba089)

![grafik](https://github.com/user-attachments/assets/d1dd236d-3003-489c-a955-c5c7010762d0)

**Comment by mman** [comment] 2024-08-06 19:37
@mr-manuel How are you accessing the app please? What browser do you use and if it is Chrome, Firefox, or Safari, could you open a web development console and see what messages get logged?

**Comment by mr-manuel** [comment] 2024-08-06 20:12
I tried with Firefox and Edge on Windows. Tried with FQDN and IP, to see if it makes a difference, but it makes not. With HTTPS it doesn't even try to make a websocket connection. In the console there is no helpful error.

Also strange that it tries to connect to port `7890` on HTTP. Probably some old code somewhere?

## Firefox HTTP working
![grafik](https://github.com/user-attachments/assets/adc03087-3e90-470d-8716-7d3ec2934d37)

![grafik](https://github.com/user-attachments/assets/70ae9c2a-c092-4606-b560-58d7d1de2568)


## Firefox HTTPS not working
![grafik](https://github.com/user-attachments/assets/31743d62-17a2-4097-a822-0e20745bdd5e)

![grafik](https://github.com/user-attachments/assets/7a602094-a76c-402e-b557-d86e10368e46)


## Edge HTTP working
![grafik](https://github.com/user-attachments/assets/27cebb09-0611-4cca-9bef-03c2a4ee1456)

![grafik](https://github.com/user-attachments/assets/8a29d056-314d-457a-94d5-c76a17325ce3)

![grafik](https://github.com/user-attachments/assets/e964612a-a6ab-4f48-981d-0aadd085e46d)


## Edge HTTPS not working
![grafik](https://github.com/user-attachments/assets/697b844b-5c55-450b-a147-3a4c53d714dd)

![grafik](https://github.com/user-attachments/assets/ea523471-29b5-4bd3-95f7-e9c131628681)

**Comment by mman** [comment] 2024-08-06 20:42
Thanks for the screenshots. How did you set up the https please? 

From the logs you sent it looks like the app is actually correctly connecting over new MQTT web socket, so that is good… but it appears to be dropping connection at some point… which is a different problem not addressed by this bug.

the fact that edge does not trust your https certificate seems also unrelated,  but is about how is the https setup… have more for me to share?

**Comment by mman** [comment] 2024-08-06 20:43
Also, the 7890 is spurious unused port, will be fixed in the next build.,.

**Comment by mr-manuel** [comment] 2024-08-06 20:47
I installed Venus OS v3.50~13 and selected the security profile `weak`, to be able to test with HTTP and HTTPS.

**Comment by mman** [comment] 2024-08-07 09:06
@mr-manuel thanks for the steps, that is precisely what I need, will try to reproduce and see what to do about it next week, I am OOO at the moment

**Comment by mman** [comment] 2024-08-13 16:06
@mr-manuel So if my understanding/testing is correct, then accessing the HTML5 app via HTTPS is not going to work at all. It's because of https://github.com/victronenergy/venus-html5-app/issues/392 where accessing insecure `ws` content when connected via `https` is refused by the browser.

I have a fix ready that allows accessing the `/app` via https properly, but it most probably does not address your connection loop issue. Could you please open another bug against this repository and add more details of what exactly are you doing and when the first connection loop occurs, and (if applicable) where the loop does not occur? I will investigate.

**Comment by mr-manuel** [comment] 2024-08-13 18:24
The connection loop is related to the same problem, so no new issue needed. Saw your opened issues. Thanks!

**Comment by mman** [comment] 2024-08-15 14:40
@mr-manuel Could you tell me more details about when you first seen the connection loop problem, and if you can reproduce it reliably? And then what should I do to reproduce it?

The thing is that currently released beta of Venus 3.50-13 only supports `http://` access to the app, and once you start using `https://` it will do nothing - it will spin with "Connecting" but the web browser log will be empty. The screenshots and logs you sent show entirely different behaviour. I'd love to learn more about how you trigger it.

Could you please send me more details?
Martin

**Comment by mr-manuel** [comment] 2024-08-15 15:00
Connection loop was probably the wrong wording. The MFD app is not connecting at all with https. I wrote connection loop because the app shows connecting forever.

**Comment by mman** [comment] 2024-08-15 15:13
> Connection loop was probably the wrong wording. The MFD app is not connecting at all with https. I wrote connection loop because the app shows connecting forever.

Yeah, that I understand... but the screenshots you have attached to this bug show different behaviour from what is expected in 3.50-13, so I wonder if there is anything else you did and as I do not want to speculate, I'd like you to explain to me step by step what steps did you do and what did and did not happen... and preferably attach a web browser development console with messages...

If all you did is updated to 3.50-13, enabled *Security Profile* *Weak* or *Secure* and tried to access the `/app` via `https://` then this is not supposed to work.

**Comment by mr-manuel** [comment] 2024-08-15 17:06
> If all you did is updated to 3.50-13, enabled Security Profile Weak or Secure and tried to access the /app via https:// then this is not supposed to work.

Yes, this are the only steps I did. So the question now to me, should it work out of the box or not?

**Comment by mman** [comment] 2024-08-15 17:56
> > If all you did is updated to 3.50-13, enabled Security Profile Weak or Secure and tried to access the /app via https:// then this is not supposed to work.
> 
> Yes, this are the only steps I did. So the question now to me is, should it work out of the box or not?

Nope, this currently is not supposed to work. Will be fixed in later beta build of Venus 3.50
